"""
OpenCodeHarness — first CodingHarness implementation.

Does NOT import or modify OpenCode core.
Communicates via:
  - optional HTTP to `opencode serve` (when available)
  - plugin callback channel registered under Spark routes
  - config generation for out-of-tree plugin

Upstream compatibility: zero patches to opencode/packages/**.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
import time
import uuid
from pathlib import Path
from typing import Any, AsyncIterator, Dict, List, Optional

from .base import EngineHandle, HarnessEvent, HarnessSession, HarnessStatus

logger = logging.getLogger(__name__)


class OpenCodeHarness:
    harness_id = "opencode"
    display_name = "OpenCode"

    def __init__(
        self,
        *,
        opencode_root: Optional[str] = None,
        spark_base_url: str = "http://127.0.0.1:7000",
        plugin_path: Optional[str] = None,
    ) -> None:
        self.opencode_root = opencode_root
        self.spark_base_url = spark_base_url.rstrip("/")
        self.plugin_path = plugin_path
        self._procs: Dict[str, asyncio.subprocess.Process] = {}
        self._queues: Dict[str, asyncio.Queue] = {}
        self._meta: Dict[str, Dict[str, Any]] = {}

    async def start(
        self,
        workspace_id: str,
        repo_root: str,
        *,
        owner: Optional[str] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> EngineHandle:
        cfg = dict(config or {})
        handle_id = uuid.uuid4().hex
        endpoint = cfg.get("endpoint")  # if OpenCode already running
        port = int(cfg.get("port") or 0)

        # Write harness-side config for plugin (never mutates OpenCode repo)
        harness_dir = Path(repo_root) / ".spark" / "harness" / "opencode"
        harness_dir.mkdir(parents=True, exist_ok=True)
        plugin_cfg = {
            "sparkUrl": cfg.get("spark_url") or self.spark_base_url,
            "token": cfg.get("token") or "",
            "workspaceId": workspace_id,
            "twinId": cfg.get("twin_id"),
            "owner": owner,
            "model": cfg.get("model"),
        }
        (harness_dir / "plugin-options.json").write_text(
            json.dumps(plugin_cfg, indent=2), encoding="utf-8"
        )
        # Example opencode config fragment (user/OpenCode loads plugin; we do not patch upstream)
        plugin_ref = self.plugin_path or self._default_plugin_path()
        example = {
            "plugin": [[plugin_ref, plugin_cfg]] if plugin_ref else [],
            "note": "Generated by Spark OpenCodeHarness — do not place inside OpenCode core.",
        }
        (harness_dir / "opencode.spark.json").write_text(
            json.dumps(example, indent=2), encoding="utf-8"
        )

        # Try to start opencode serve if binary/bun available and no endpoint given
        if not endpoint:
            endpoint, port, proc = await self._try_start_server(repo_root, port or 4096)
            if proc:
                self._procs[handle_id] = proc

        self._meta[handle_id] = {
            "repo_root": repo_root,
            "workspace_id": workspace_id,
            "owner": owner,
            "config": cfg,
            "harness_dir": str(harness_dir),
        }

        return EngineHandle(
            handle_id=handle_id,
            harness_id=self.harness_id,
            workspace_id=workspace_id,
            endpoint=endpoint,
            pid=self._procs[handle_id].pid if handle_id in self._procs else None,
            metadata={
                "repo_root": repo_root,
                "plugin_config": str(harness_dir / "plugin-options.json"),
                "mode": "http" if endpoint else "plugin-only",
            },
        )

    async def stop(self, handle: EngineHandle) -> None:
        proc = self._procs.pop(handle.handle_id, None)
        if proc and proc.returncode is None:
            try:
                proc.terminate()
                try:
                    await asyncio.wait_for(proc.wait(), timeout=5)
                except asyncio.TimeoutError:
                    proc.kill()
            except Exception as exc:
                logger.debug("stop opencode: %s", exc)
        self._meta.pop(handle.handle_id, None)

    async def create_session(
        self,
        handle: EngineHandle,
        *,
        model: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> HarnessSession:
        sid = uuid.uuid4().hex
        external = None
        # Best-effort: create session via OpenCode HTTP if endpoint known
        if handle.endpoint:
            external = await self._http_create_session(handle.endpoint, model=model)
        self._queues[sid] = asyncio.Queue()
        return HarnessSession(
            session_id=sid,
            handle_id=handle.handle_id,
            workspace_id=handle.workspace_id,
            harness_id=self.harness_id,
            external_id=external or sid,
            model=model,
            metadata={
                **(metadata or {}),
                "endpoint": handle.endpoint,
                "engine": "opencode",
            },
        )

    async def send(
        self,
        session: HarnessSession,
        message: str,
        *,
        attachments: Optional[List[Dict[str, Any]]] = None,
    ) -> None:
        endpoint = (session.metadata or {}).get("endpoint")
        q = self._queues.setdefault(session.session_id, asyncio.Queue())
        if endpoint and session.external_id:
            ok = await self._http_send(endpoint, session.external_id, message)
            if ok:
                await q.put(
                    HarnessEvent(
                        type="status",
                        session_id=session.session_id,
                        payload={"sent": True, "via": "http"},
                        ts=time.time(),
                    )
                )
                return
        # Plugin-only / offline mode: emit advisory event (OpenCode TUI may be used externally)
        await q.put(
            HarnessEvent(
                type="status",
                session_id=session.session_id,
                payload={
                    "sent": False,
                    "mode": "external",
                    "hint": (
                        "OpenCode HTTP not available. Use OpenCode UI with Spark plugin "
                        "configured at .spark/harness/opencode/opencode.spark.json"
                    ),
                    "message_queued": message[:500],
                },
                ts=time.time(),
            )
        )
        await q.put(
            HarnessEvent(
                type="done",
                session_id=session.session_id,
                payload={"external_ui": True},
                ts=time.time(),
            )
        )

    async def stream(self, session: HarnessSession) -> AsyncIterator[HarnessEvent]:
        q = self._queues.setdefault(session.session_id, asyncio.Queue())
        while True:
            try:
                ev = await asyncio.wait_for(q.get(), timeout=120.0)
            except asyncio.TimeoutError:
                yield HarnessEvent(
                    type="status",
                    session_id=session.session_id,
                    payload={"waiting": True},
                    ts=time.time(),
                )
                continue
            yield ev
            if ev.type in ("done", "error"):
                break

    async def cancel(self, session: HarnessSession) -> None:
        q = self._queues.setdefault(session.session_id, asyncio.Queue())
        await q.put(
            HarnessEvent(
                type="done",
                session_id=session.session_id,
                payload={"cancelled": True},
                ts=time.time(),
            )
        )

    async def status(self, handle: EngineHandle) -> HarnessStatus:
        proc = self._procs.get(handle.handle_id)
        if proc and proc.returncode is None:
            return HarnessStatus(
                handle_id=handle.handle_id,
                harness_id=self.harness_id,
                state="running",
                detail=f"endpoint={handle.endpoint}",
                metadata={"pid": proc.pid},
            )
        if handle.endpoint:
            healthy = await self._http_health(handle.endpoint)
            return HarnessStatus(
                handle_id=handle.handle_id,
                harness_id=self.harness_id,
                state="running" if healthy else "unhealthy",
                detail=handle.endpoint or "",
            )
        return HarnessStatus(
            handle_id=handle.handle_id,
            harness_id=self.harness_id,
            state="running",
            detail="plugin-only / external OpenCode",
            metadata=self._meta.get(handle.handle_id) or {},
        )

    # ── helpers ───────────────────────────────────────────────────────

    def _default_plugin_path(self) -> Optional[str]:
        # Prefer Spark integrations path
        candidates = [
            Path(__file__).resolve().parents[2] / "integrations" / "opencode" / "plugin",
        ]
        for c in candidates:
            if c.is_dir():
                return str(c)
        return None

    async def _try_start_server(
        self, repo_root: str, port: int
    ) -> tuple[Optional[str], int, Optional[asyncio.subprocess.Process]]:
        bun = shutil.which("bun")
        opencode_bin = shutil.which("opencode")
        cmd = None
        cwd = repo_root
        if opencode_bin:
            cmd = [opencode_bin, "serve", "--port", str(port)]
        elif bun and self.opencode_root and Path(self.opencode_root).is_dir():
            entry = Path(self.opencode_root) / "packages" / "opencode" / "src" / "index.ts"
            if entry.is_file():
                cmd = [bun, "run", str(entry), "serve", "--port", str(port)]
                cwd = self.opencode_root
        if not cmd:
            logger.info("OpenCode binary not found — harness runs in plugin-only mode")
            return None, port, None
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                cwd=cwd,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            # brief wait for listen
            await asyncio.sleep(0.8)
            endpoint = f"http://127.0.0.1:{port}"
            if proc.returncode is not None:
                logger.warning("OpenCode serve exited early code=%s", proc.returncode)
                return None, port, None
            return endpoint, port, proc
        except Exception as exc:
            logger.warning("Failed to start OpenCode serve: %s", exc)
            return None, port, None

    async def _http_health(self, endpoint: str) -> bool:
        try:
            import urllib.request
            def _get():
                req = urllib.request.Request(endpoint.rstrip("/") + "/global/health", method="GET")
                with urllib.request.urlopen(req, timeout=2) as resp:
                    return 200 <= resp.status < 300
            return await asyncio.to_thread(_get)
        except Exception:
            try:
                import urllib.request
                def _get2():
                    req = urllib.request.Request(endpoint.rstrip("/") + "/", method="GET")
                    with urllib.request.urlopen(req, timeout=2) as resp:
                        return True
                return await asyncio.to_thread(_get2)
            except Exception:
                return False

    async def _http_create_session(self, endpoint: str, model: Optional[str]) -> Optional[str]:
        # OpenCode HTTP shapes evolve; best-effort only
        try:
            import urllib.request
            body = json.dumps({"model": model} if model else {}).encode()
            def _post():
                req = urllib.request.Request(
                    endpoint.rstrip("/") + "/session",
                    data=body,
                    headers={"Content-Type": "application/json"},
                    method="POST",
                )
                with urllib.request.urlopen(req, timeout=5) as resp:
                    data = json.loads(resp.read().decode() or "{}")
                    return data.get("id") or data.get("sessionID") or data.get("session_id")
            return await asyncio.to_thread(_post)
        except Exception as exc:
            logger.debug("opencode create session: %s", exc)
            return None

    async def _http_send(self, endpoint: str, session_id: str, message: str) -> bool:
        try:
            import urllib.request
            body = json.dumps({"parts": [{"type": "text", "text": message}]}).encode()
            def _post():
                for path in (
                    f"/session/{session_id}/message",
                    f"/session/{session_id}/prompt",
                ):
                    try:
                        req = urllib.request.Request(
                            endpoint.rstrip("/") + path,
                            data=body,
                            headers={"Content-Type": "application/json"},
                            method="POST",
                        )
                        with urllib.request.urlopen(req, timeout=10) as resp:
                            if 200 <= resp.status < 300:
                                return True
                    except Exception:
                        continue
                return False
            return await asyncio.to_thread(_post)
        except Exception:
            return False


def register_opencode_harness(
    registry,
    *,
    opencode_root: Optional[str] = None,
    spark_base_url: str = "http://127.0.0.1:7000",
    plugin_path: Optional[str] = None,
) -> None:
    def factory():
        return OpenCodeHarness(
            opencode_root=opencode_root,
            spark_base_url=spark_base_url,
            plugin_path=plugin_path,
        )
    registry.register(
        "opencode",
        factory,
        display_name="OpenCode",
        metadata={"upstream": "anomalyco/opencode", "core_patches": []},
    )
